In [1]:
import pandas as pd
df=pd.read_csv("oregon_real_estate_2026_ultimate.csv")
print(df)
df.head()

                type   sub_type  \
0      single_family        NaN
1      single_family        NaN
2             condos      condo
3      single_family        NaN
4             condos      condo
...              ...        ...
10398      townhomes  townhouse
10399  single_family        NaN
10400  single_family        NaN
10401      townhomes  townhouse
10402         condos      condo

                                                    text  listPrice    sqft  \
0      Showings subject to accepted offer. Investor o...   179950.0   698.0
1      *DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...   399900.0  2736.0
2      This exceptional property is priced to sell & ...   220000.0  1130.0
3      Commercially zoned property currently utilized...   230000.0  1293.0
4      Sophisticated and beautifully updated riverfro...   899000.0  3172.0
...                                                  ...        ...     ...
10398  New Construction, Brynhill Community, Daphne F...   329900.0  1441.0
10399  Light and bright bungalow on .25 acre lot. (Zo...   415000.0  1238.0
10400  This is one of the very best floating home loc...   750000.0     NaN
10401  Live new without the new-construction wait in ...   387500.0  1332.0
10402  STUNNING 3 MOUNTAIN AND COLUMBIA RIVER VIEW......   510000.0  2667.0

       stories  beds  baths  baths_full  baths_full_calc  garage  year_built
0          1.0   2.0    1.0         1.0              1.0     NaN      1897.0
1          2.0   4.0    2.0         2.0              2.0     2.0      1990.0
2          1.0   3.0    3.0         3.0              3.0     NaN      2011.0
3          2.0   3.0    2.0         2.0              2.0     1.0      1956.0
4          3.0   3.0    4.0         4.0              4.0     1.0      2006.0
...        ...   ...    ...         ...              ...     ...         ...
10398      2.0   3.0    2.0         2.0              2.0     2.0      2026.0
10399      2.0   2.0    1.0         1.0              1.0     1.0      1953.0
10400      NaN   1.0    1.0         NaN              NaN     NaN         NaN
10401      2.0   2.0    2.0         2.0              2.0     1.0      2025.0
10402      3.0   3.0    3.0         3.0              3.0     2.0      2000.0

[10403 rows x 12 columns]

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2.0,1.0,1.0,1.0,NaN,1897.0
1,single_family,NaN,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4.0,2.0,2.0,2.0,2.0,1990.0
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3.0,3.0,3.0,3.0,NaN,2011.0
3,single_family,NaN,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3.0,2.0,2.0,2.0,1.0,1956.0
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3.0,4.0,4.0,4.0,1.0,2006.0

In [4]:
df.head()

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2.0,1.0,1.0,1.0,NaN,1897.0
1,single_family,NaN,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4.0,2.0,2.0,2.0,2.0,1990.0
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3.0,3.0,3.0,3.0,NaN,2011.0
3,single_family,NaN,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3.0,2.0,2.0,2.0,1.0,1956.0
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3.0,4.0,4.0,4.0,1.0,2006.0

In [3]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop("baths",axis=1)

,type,sub_type,text,listPrice,sqft,stories,beds,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2.0,1.0,1.0,NaN,1897.0
1,single_family,NaN,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4.0,2.0,2.0,2.0,1990.0
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3.0,3.0,3.0,NaN,2011.0
3,single_family,NaN,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3.0,2.0,2.0,1.0,1956.0
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3.0,4.0,4.0,1.0,2006.0
...,...,...,...,...,...,...,...,...,...,...,...
10398,townhomes,townhouse,"New Construction, Brynhill Community, Daphne F...",329900.0,1441.0,2.0,3.0,2.0,2.0,2.0,2026.0
10399,single_family,NaN,Light and bright bungalow on .25 acre lot. (Zo...,415000.0,1238.0,2.0,2.0,1.0,1.0,1.0,1953.0
10400,single_family,NaN,This is one of the very best floating home loc...,750000.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
10401,townhomes,townhouse,Live new without the new-construction wait in ...,387500.0,1332.0,2.0,2.0,2.0,2.0,1.0,2025.0
10402,condos,condo,STUNNING 3 MOUNTAIN AND COLUMBIA RIVER VIEW......,510000.0,2667.0,3.0,3.0,3.0,3.0,2.0,2000.0

In [ ]:
df.isna().sum()

type                  0
sub_type           9058
text                 19
listPrice             0
sqft               2076
stories            2214
beds               2069
baths              2002
baths_full         2092
baths_full_calc    2090
garage             3763
year_built         2360
dtype: int64

In [ ]:
df.notnull().sum()

type               10403
sub_type            1345
text               10384
listPrice          10403
sqft                8327
stories             8189
beds                8334
baths               8401
baths_full          8311
baths_full_calc     8313
garage              6640
year_built          8043
dtype: int64

In [10]:
df["year_built"]=df["year_built"].fillna(df["year_built"].median())
df.head()

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2.0,1.0,1.0,1.0,NaN,1897.0
1,single_family,NaN,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4.0,2.0,2.0,2.0,2.0,1990.0
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3.0,3.0,3.0,3.0,NaN,2011.0
3,single_family,NaN,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3.0,2.0,2.0,2.0,1.0,1956.0
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3.0,4.0,4.0,4.0,1.0,2006.0

In [12]:
df["year_built"]=df["year_built"].astype(int)
df.head()

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2.0,1.0,1.0,1.0,NaN,1897
1,single_family,NaN,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4.0,2.0,2.0,2.0,2.0,1990
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3.0,3.0,3.0,3.0,NaN,2011
3,single_family,NaN,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3.0,2.0,2.0,2.0,1.0,1956
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3.0,4.0,4.0,4.0,1.0,2006

In [23]:
df.dropna(inplace=True)
df.head(12)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,price_per_sqft
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3.0,3.0,3.0,3.0,0,2011,194.690265
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3.0,4.0,4.0,4.0,1,2006,283.417402
13,condos,condo,Welcome to Unit #2 at the iconic Overlook Cond...,325000.0,691.0,1.0,1.0,1.0,1.0,1.0,0,1920,470.332851
85,townhomes,townhouse,"Tucked into the natural beauty of Westfir, [Re...",204000.0,900.0,1.0,3.0,2.0,2.0,2.0,0,1949,226.666667
133,townhomes,townhouse,Beautiful light-filled corner home in the hear...,469000.0,1612.0,2.0,3.0,2.0,2.0,2.0,2,2022,290.942928
146,condos,condo,Charming corner unit move-in ready condo with ...,349900.0,1593.0,1.0,2.0,2.0,2.0,2.0,1,1980,219.648462
158,condos,condo,Huge Price Reduction! Historic & charming 2-be...,199950.0,922.0,1.0,2.0,1.0,1.0,1.0,0,1915,216.865510
173,condos,condo,"Four bedroom, two bath townhome-style condo av...",227500.0,1611.0,2.0,4.0,2.0,2.0,2.0,2,1978,141.216636
235,condos,condo,"This 1911-built, 761 sq ft, 1 bedroom, 1 bathr...",99900.0,761.0,1.0,1.0,1.0,1.0,1.0,0,1911,131.274639
259,condos,condo,Prime West Side Bend ground-level condo just m...,329000.0,548.0,1.0,1.0,1.0,1.0,1.0,0,1992,600.364964
279,townhomes,townhouse,Discover exceptional living at [Redacted Entit...,525000.0,1692.0,3.0,3.0,3.0,3.0,3.0,2,2021,310.283688
291,townhomes,townhouse,"Welcome to this charming 3 bed, [Redacted Enti...",289500.0,14051.0,1.0,3.0,2.0,2.0,2.0,0,2023,20.603516

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10403 entries, 0 to 10402
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             10403 non-null  str
 1   sub_type         1345 non-null   str
 2   text             10384 non-null  str
 3   listPrice        10403 non-null  float64
 4   sqft             8327 non-null   float64
 5   stories          8189 non-null   float64
 6   beds             8334 non-null   float64
 7   baths            8401 non-null   float64
 8   baths_full       8311 non-null   float64
 9   baths_full_calc  8313 non-null   float64
 10  garage           6640 non-null   float64
 11  year_built       8043 non-null   float64
dtypes: float64(9), str(3)
memory usage: 975.4 KB

In [12]:
df["beds"]=df["beds"].fillna(0,inplace=True).astype(int)
df["baths"]=df["baths"].fillna(0,inplace=True).astype(int)
df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_22036\2275708763.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["beds"]=df["beds"].fillna(0,inplace=True).astype(int)
C:\Users\HP\AppData\Local\Temp\ipykernel_22036\2275708763.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["baths"]=df["baths"].fillna(0,inplace=True).astype(int)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,price_per_sqft
0,single_family,NaN,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2,1,1.0,1.0,0,1897.0,257.808023
1,single_family,NaN,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4,2,2.0,2.0,2,1990.0,146.162281
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3,3,3.0,3.0,0,2011.0,194.690265
3,single_family,NaN,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3,2,2.0,2.0,1,1956.0,177.880897
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3,4,4.0,4.0,1,2006.0,283.417402

In [5]:
df["garage"]=df["garage"].fillna(0,inplace=True)
df["garage"]=df["garage"].astype(int)
df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_22036\3437835981.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["garage"]=df["garage"].fillna(0,inplace=True)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built
0,single_family,NaN,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2.0,1.0,1.0,1.0,0,1897.0
1,single_family,NaN,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4.0,2.0,2.0,2.0,2,1990.0
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3.0,3.0,3.0,3.0,0,2011.0
3,single_family,NaN,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3.0,2.0,2.0,2.0,1,1956.0
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3.0,4.0,4.0,4.0,1,2006.0

In [ ]:
# df = df.convert_dtypes()
# df.head()

In [7]:
df.isna().sum()

type                  0
sub_type           9058
text                 19
listPrice             0
sqft               2076
stories            2214
beds               2069
baths              2002
baths_full         2092
baths_full_calc    2090
garage                0
year_built         2360
dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10403 entries, 0 to 10402
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             10403 non-null  str
 1   sub_type         1345 non-null   str
 2   text             10384 non-null  str
 3   listPrice        10403 non-null  float64
 4   sqft             8327 non-null   float64
 5   stories          8189 non-null   float64
 6   beds             8334 non-null   float64
 7   baths            8401 non-null   float64
 8   baths_full       8311 non-null   float64
 9   baths_full_calc  8313 non-null   float64
 10  garage           6640 non-null   float64
 11  year_built       8043 non-null   float64
dtypes: float64(9), str(3)
memory usage: 975.4 KB

In [13]:
# df["beds"]=df["beds"].fillna(df["beds"].mean())
df["sub_type"]=df["sub_type"].fillna("unknown")
df.head(30)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,price_per_sqft
0,single_family,unknown,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2,1,1.0,1.0,0,1897.0,257.808023
1,single_family,unknown,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4,2,2.0,2.0,2,1990.0,146.162281
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3,3,3.0,3.0,0,2011.0,194.690265
3,single_family,unknown,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3,2,2.0,2.0,1,1956.0,177.880897
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3,4,4.0,4.0,1,2006.0,283.417402
5,single_family,unknown,"Fantastic value & room to grow. Upstairs, a br...",475000.0,1959.0,2.0,3,2,2.0,2.0,2,1997.0,242.470648
6,single_family,unknown,An opportunity awaits! Discover the perfect bl...,379900.0,1484.0,1.0,3,1,1.0,1.0,2,1967.0,255.997305
7,single_family,unknown,"Very large 4,328 sq ft 5 bedroom 3 bath home w...",650000.0,4328.0,2.0,5,3,3.0,3.0,2,1975.0,150.184843
8,single_family,unknown,New attractive price for this historic Craftsm...,459000.0,2043.0,2.0,3,1,1.0,1.0,2,1921.0,224.669604
9,single_family,unknown,"Just Listed! Brand New Community ""Sky Terrace""...",649950.0,2375.0,3.0,4,3,3.0,3.0,2,2026.0,273.663158
10,single_family,unknown,"Charming Salem home blending comfort, updates,...",343900.0,1408.0,1.0,2,1,1.0,1.0,1,1946.0,244.247159
11,single_family,unknown,Own a slice of Sunriver at a fraction of the c...,78000.0,1806.0,3.0,3,2,2.0,2.0,0,1970.0,43.189369
12,single_family,unknown,Fixer Opportunity. Set on high ground with vie...,315000.0,748.0,2.0,2,1,1.0,1.0,1,1936.0,421.122995
13,condos,condo,Welcome to Unit #2 at the iconic Overlook Cond...,325000.0,691.0,1.0,1,1,1.0,1.0,0,1920.0,470.332851
14,single_family,unknown,This stunning single-level home in Sunset Glen...,699900.0,1843.0,1.0,3,2,2.0,2.0,2,NaN,379.761259
15,single_family,unknown,Prime location on the Oregon Coast! Say goodby...,95000.0,1150.0,1.0,3,2,2.0,2.0,0,2007.0,82.608696
16,single_family,unknown,Cabin in the Blue Mountains! Charming 1-bedroo...,159000.0,1040.0,2.0,1,1,1.0,1.0,0,1987.0,152.884615
17,land,unknown,Owner financing available! Explore and enjoy 5...,3300.0,NaN,NaN,0,0,NaN,NaN,0,NaN,NaN
18,single_family,unknown,Discover the potential to create your dream co...,239000.0,1638.0,1.0,3,1,1.0,1.0,2,1900.0,145.909646
19,farm,unknown,Turnkey Irrigated Farm with Established Infras...,4950000.0,1620.0,NaN,4,2,2.0,2.0,0,1999.0,3055.555556
20,single_family,unknown,"Discover modern living in Starview, SW Redmond...",679900.0,2660.0,2.0,5,3,3.0,3.0,2,NaN,255.601504
21,single_family,unknown,Just finished & priced to sell on day ONE! Thi...,465000.0,1400.0,2.0,3,2,2.0,2.0,1,2026.0,332.142857
22,single_family,unknown,Experience Net-Zero Solar Living in the Heart ...,650000.0,1207.0,1.0,3,2,2.0,2.0,1,NaN,538.525269
23,single_family,unknown,"Conveniently located just 3 miles from I-5, th...",749900.0,2438.0,2.0,3,3,2.0,2.0,2,1974.0,307.588187
24,land,unknown,Here's your chance to own 1/[Redacted Entity] ...,210000.0,NaN,NaN,0,0,NaN,NaN,0,NaN,NaN
25,single_family,unknown,Caldera Springs features miles of trails along...,2149000.0,3910.0,2.0,4,4,4.0,4.0,3,NaN,549.616368
26,single_family,unknown,Picture slow mornings in a sun-filled room wra...,474900.0,2214.0,1.0,4,2,2.0,2.0,2,2016.0,214.498645
27,single_family,unknown,Escape to your private Eastern Oregon retreat ...,895000.0,3684.0,2.0,4,3,3.0,3.0,3,1999.0,242.942454
28,single_family,unknown,This home has the kind of character and charm ...,375000.0,1704.0,2.0,2,2,2.0,2.0,1,1938.0,220.070423
29,single_family,unknown,Wonderful property with Elk Creek running thro...,189000.0,1538.0,1.0,4,1,1.0,1.0,2,1948.0,122.886866

In [14]:
df["price_per_sqft"] = df["listPrice"] / df["sqft"]
df.head()

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,price_per_sqft
0,single_family,unknown,Showings subject to accepted offer. Investor o...,179950.0,698.0,1.0,2,1,1.0,1.0,0,1897.0,257.808023
1,single_family,unknown,*DO NOT DRIVE BY WITHOUT AN APPOINTMENT* Distr...,399900.0,2736.0,2.0,4,2,2.0,2.0,2,1990.0,146.162281
2,condos,condo,This exceptional property is priced to sell & ...,220000.0,1130.0,1.0,3,3,3.0,3.0,0,2011.0,194.690265
3,single_family,unknown,Commercially zoned property currently utilized...,230000.0,1293.0,2.0,3,2,2.0,2.0,1,1956.0,177.880897
4,condos,condo,Sophisticated and beautifully updated riverfro...,899000.0,3172.0,3.0,3,4,4.0,4.0,1,2006.0,283.417402